// @file: packages/types/src/user.ts
export enum UserRole {
  ROOT = "ROOT",
  SYSTEM = "SYSTEM",
  ADMIN = "ADMIN",
  SKARBNIK = "SKARBNIK",
  SKARBNIK_REGION = "SKARBNIK_REGION",
  USER = "USER",
}

export enum UserRegion {
  ALL = "ALL",
  DOLNOSLASKI = "DOLNOSLASKI",
  GORNOSLASKI = "GORNOSLASKI",
  KUJAWSKO_POMORSKI = "KUJAWSKO_POMORSKI",
  LUBELSKI = "LUBELSKI",
  LODZKI = "LODZKI",
  MALOPOLSKI = "MALOPOLSKI",
  MAZOWIECKI = "MAZOWIECKI",
  PODKARPACKI = "PODKARPACKI",
  POMORSKI = "POMORSKI",
  POLNOCNO_ZACHODNI = "POLNOCNO_ZACHODNI",
  STAROPOLSKI = "STAROPOLSKI",
  WIELKOPOLSKI = "WIELKOPOLSKI",
  NONE = "NONE",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY",
}